# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jearim Modesto
email: jearimmodesto@gmail.com
first_name: Luis
middle_name: Jearim
last_name: Modesto
description: >- # this means to ignore newlines until "baseurl:"
  "Success is not final, failure is not fatal: It is the courage to continue that counts." - Winston Churchill
baseurl: "" # the subpath of your site, e.g. /blog
domain: JearimModesto.github.io
url: https://JearimModesto.github.io  # the base hostname & protocol for your site, e.g. http://example.com
keywords: jekyll, jekyll-theme, academic-website, portfolio-website
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.

lang: en # the language of your site (for example: en, fr, cn, ru, etc.)
icon: /assets/img/mainIcon.svg  # the emoji used as the favicon (alternatively, provide image name in /assets/img/)


github_username:  RepellantHail
linkedin_username: jearimmodesto
hackerrank_username: jearimmodesto

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/