import { Inter } from 'next/font/google'
import './globals.css'
import 'bootstrap/dist/css/bootstrap.css'
import Navbar from './Navbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Luis Modesto',
  description: 'Generated by Next.js',  
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  )
}
